# ansible_IP_check.yml - N.J.Holmes February 2018
#
# test IP connectivity for list of IP addresses and ports
#
# version 1.0
#
---
- hosts: MMSC_EK_Nodes_ML,MMSC_NN_Nodes_ML
#- hosts:  MMSC_EK_Nodes_ML,MMSC_NN_Nodes_ML,VMAIL_EK_ML,VMAIL_NN_ML
#- hosts:  IPSMGW_EK_ALL_PR,IPSMGW_NN_ALL_PR
#- hosts:  IPSMGW_EK_AM_PR,IPSMGW_MY_AM_PR
  remote_user: root
  gather_facts: false
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    device: "{{hostvars[inventory_hostname].dev}}"
    subnet: "{{ inventory_hostname.split('.')[2]  }}"
    list_ip_addr: [ 10.33.16.52, 10.33.16.53, 10.33.208.52, 10.33.208.53, 10.33.18.10, 10.33.18.11, 10.33.18.12, 10.33.18.13, 10.33.18.14, 10.33.18.15, 10.33.18.16, 10.33.18.17, 10.33.18.18, 10.33.18.19, 10.33.18.20, 10.33.18.21, 10.33.18.22, 10.33.18.23, 10.33.18.24, 10.33.18.25, 10.33.18.26, 10.33.18.27, 10.33.210.10, 10.33.210.11, 10.33.210.12, 10.33.210.13, 10.33.210.14, 10.33.210.15, 10.33.210.16, 10.33.210.17, 10.33.210.18, 10.33.210.19, 10.33.210.20, 10.33.210.21, 10.33.210.22, 10.33.210.23, 10.33.210.24, 10.33.210.25, 10.33.210.26, 10.33.210.27 ]
    list_ports: [ 9997 ]

  tasks:
        
    # Test the connections
    - name: Test the connections
      wait_for: 
        host={{ item[0] }} 
        port={{ item[1] }} 
        timeout=1
#        #msg="Timeout to IP {{ item[0] }} port {{ item[1] }}" # not available under 2.3 only 2.4 onwards
      with_nested:
        - "{{ list_ip_addr }}"
        - "{{ list_ports }}"
      ignore_errors: yes


    # Test the connections with a custom module
#    - name: Test the connections with custom module can_reach.py
#      can_reach:
#        host={{ item[0] }}
#        port={{ item[1] }}
#        timeout=1
#      with_nested:
#        - "{{ list_ip_addr }}"
#        - "{{ list_ports }}"
#      ignore_errors: yes

